### ISSUE TITLE
Bug in Schedule class

### ISSUE THREAD

**Issue by dlsoltero** [LiuLab-Bioelectronics-Harvard/UnitedNet#10]
Hello,
I got an error while trying to run UnitedNet on a dataset I have, while checking this error I noticed that the lines 152-164 in file src/scripts.py, re-declare the self.optimizer, self.losses, and self.best_loss_term variables that were just declare a few lines before for the translation schedules. 

Commenting these lines fixed my issue but I'm not familiar enough with the architecture to know which of the two losses declared in this section are the correct ones. I'd appreciate the clarification.

Best,

**Comment by virgiliokmetzsch** [comment]
This correction solved the issue, I'm now successfully running DLPFC.ipynb to train the network.

Thank you very much for your help!
