### ISSUE TITLE
RuntimeError: weight tensor should be defined either for all 12 classes or no classes but got weight tensor of shape: [13]

### ISSUE THREAD

**Issue by xu15825503775** [LiuLab-Bioelectronics-Harvard/UnitedNet#5]
RuntimeError                              Traceback (most recent call last)
Cell In[12], line 11
      7     model = UnitedNet(root_save_path, device=device, technique=dbitseq_config)
      9     print(model)
---> 11     model.train(adatas_train,verbose=True)
     12     model.finetune(adatas_all,verbose=True)
     13 else:

File ~\Desktop\新建文件夹\UnitedNet-main\UnitedNet-main\notebooks\..\src\interface.py:190, in UnitedNet.train(self, adatas_train, save_path, adatas_val, init_classify, verbose)
    184             self._set_device()
    187 #         print("model.config:",self.model.config)
--> 190         run_train(
    191             self.model, dataloader_train, dataloader_test,verbose=verbose
    192         )

File ~\Desktop\新建文件夹\UnitedNet-main\UnitedNet-main\notebooks\..\src\scripts.py:376, in run_train(model, dataloader_train, dataloader_val, verbose)
    374 model.train()
    375 for schedule in schedules:
--> 376     run_through_dataloader(model, dataloader_train, schedule, train_model=True)
    378 model.eval()
    379 with torch.no_grad():

File ~\Desktop\新建文件夹\UnitedNet-main\UnitedNet-main\notebooks\..\src\scripts.py:240, in run_schedule.<locals>.wrapper_run_schedule(model, dataloader, schedule, train_model, infer_model, best_model_path, give_losses, verbose)
    238     return outputs
    239 else:
--> 240     return runner(
    241         model, dataloader, schedule, train_model, infer_model, best_model_path,
    242         give_losses=give_losses, verbose=verbose
    243     )

File ~\Desktop\新建文件夹\UnitedNet-main\UnitedNet-main\notebooks\..\src\scripts.py:265, in run_through_dataloader(model, dataloader, schedule, train_model, infer_model, best_model_path, give_losses, verbose)
    263 outputs = model(modalities, labels)
    264 if schedule is not None:
--> 265     losses = schedule.step(model, train_model)
    266     losses = amplify_value_dictionary_by_sample_size(losses, len(labels))
    267     all_losses = sum_value_dictionaries(all_losses, losses)

File ~\Desktop\新建文件夹\UnitedNet-main\UnitedNet-main\notebooks\..\src\scripts.py:176, in Schedule.step(self, model, train_model)
    174 for loss in self.losses:
    175     if loss.name in [str_self_entropy_loss, str_ddc_loss, str_cross_entropy_loss]:
--> 176         _, head_losses = loss(model)
    177         for hd, h_ls in enumerate(head_losses):
    178             losses[f'{loss.name}_head_{hd}'] = h_ls

File ~\Desktop\新建文件夹\UnitedNet-main\UnitedNet-main\notebooks\..\src\loss.py:207, in CrossEntropyLoss.__call__(self, model)
    204 head_losses = []
    206 for cluster_outputs in model.cluster_outputs:
--> 207     loss = F.cross_entropy(
    208         cluster_outputs, model.labels, weight=self.class_weights,
    209     )
    211     loss /= model.n_head
    212     loss *= self.weight

File D:\Anaconda3\envs\deepst\lib\site-packages\torch\nn\functional.py:3029, in cross_entropy(input, target, weight, size_average, ignore_index, reduce, reduction, label_smoothing)
   3027 if size_average is not None or reduce is not None:
   3028     reduction = _Reduction.legacy_get_string(size_average, reduce)
-> 3029 return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)

RuntimeError: weight tensor should be defined either for all 12 classes or no classes but got weight tensor of shape: [13]

**Comment by qpmnh** [comment]
应该是这个参数self.class_weights有问题

**Comment by xu15825503775** [comment]
I wonder how to modify it.I would appreciate it if you could tell me.




---Original---
From: ***@***.***&gt;
Date: Fri, Jun 2, 2023 09:19 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [LiuLab-Bioelectronics-Harvard/UnitedNet] RuntimeError: weighttensor should be defined either for all 12 classes or no classes but gotweight tensor of shape: [13] (Issue #5)




 
应该是这个参数self.class_weights有问题
